spring.application.name=LiveDemoHibernate


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/javalivedemo2026
spring.datasource.username=demoUser
spring.datasource.password=secretPassword
